name: CI

on:
  push:
    branches:
      - main
      - next
  pull_request:

jobs:
  lint:
    name: Quality checks

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      - name: Lint
        run: yarn eslint .

      - name: Check formatting
        run: yarn prettier . --check

  test:
    name: Test - ${{ matrix.os }} - Node v${{ matrix.node-version }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node-version: [20.x, 22.x]
      fail-fast: false

    runs-on: ${{ matrix.os }}

    steps:
      - name: Set up Git
        if: matrix.os == 'windows-latest'
        run: git config --global core.autocrlf input

      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      - name: Run tests
        run: yarn test
